package:
    name: ksif
    version: v20200305

build:
    number: 20200305

source:
    git_url: ./

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - setuptools >=3.3
    - python-dateutil >=2.5.0
    - pytz
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.5.0
    - pytz
    - pandas
    - numpy
    - matplotlib
    - scikit
    - scipy
    - statsmodels
    - patsy
    - performanceanalytics
    - tqdm
    - requests
    - tables
    - python-dateutil
    - urllib3
    - xlrd

test:
  requires:
    - pytest
  commands:
    - python -c "import pandas; pandas.test()"


about:
  home: https://github.com/sangheumcho/ksif
  license: MIT